version: '3'

services:
  root_node:
    image: kademlia-app
    networks:
      kademlia_network:
        ipv4_address: 172.16.238.10  # Static IP for the root node
    ports:
      - "8080:8080"  # Expose root node's port to host for debugging purposes

  kademlia_node:
    image: kademlia-app
    environment:
      - CONTACT_ADDRESS=172.16.238.10:8080  # Contact root node via its static IP
    depends_on:
      - root_node
    networks:
      - kademlia_network
    deploy:
      replicas: 5


networks:
  kademlia_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24  # Manually configure the subnet for static IPs
